# Dockerfile

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# [NEW] Install dependencies required for mysqlclient
RUN apt-get update && apt-get install -y \
    pkg-config \
    gcc \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Removed apt-get install libpq-dev since we don't need Postgres drivers

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# We can keep the entrypoint if you want to run migrations automatically,
# or simply use the command directly in docker-compose.
# Copy the entrypoint script
COPY entrypoint.sh /app/entrypoint.sh

# Make it executable (Critical step!)
RUN chmod +x /app/entrypoint.sh

# Set it as the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]
